# Generated by Django 5.1.3 on 2024-12-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent')),
            ],
        ),
    ]
